# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alphalink', '__first__'),
        ('dcim', '0032_device_increase_name_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='alphalink.Cluster'),
        ),
    ]
