# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 18:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utilities.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('comments', models.TextField(blank=True)),
                ('cpu', models.PositiveSmallIntegerField(default=12, help_text=b'Number of CPU in cluster', verbose_name=b'CPU Number')),
                ('memory', models.PositiveIntegerField(default=8192, help_text=b'Total memory (in MB) in cluster', verbose_name=b'Memory (MB)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
